import test from 'node:test'; import assert from 'node:assert/strict';
import { coding, unit, provenance, service, workItem, transitionWork, acquisition, mediaObject, diagnosticValue, observation, interpretation, transitionResult, verification, assertSameClinicalContext, DomainError } from '../src/canonical.js';
import { observationApi } from '../src/api.js';
const now='2026-09-08T00:00:00.000Z'; const p=provenance({sourceType:'synthetic-fixture',sourceId:'fixture',recordedAt:now}); const base={organizationId:'org-a',siteId:'site-a',patientId:'patient-a',orderId:'order-a'};
function makeObservation(modality, type='quantity') { const svc=service({organizationId:'org-a',code:{code:`local-${modality}`,system:'urn:synthetic'},name:`Synthetic ${modality}`,modality}); const work=workItem({...base,serviceId:svc.id,provenance:p}); const acquired=acquisition({...base,workItemId:work.id,performedAt:now,provenance:p}); return observation({...base,acquisitionId:acquired.id,code:{code:'local-observation',system:'urn:synthetic'},value:type==='text'?{type:'text',value:'synthetic'}:{type:'quantity',value:1,valueUnit:unit({code:'synthetic-unit',system:'urn:synthetic'})},effectiveAt:now,issuedAt:now,provenance:p}); }
test('one canonical model represents synthetic ECG, PFT, X-ray, CT, MRI, laboratory, and pathology fixtures', () => { for (const modality of ['ECG','PFT','X-ray','CT','MRI','laboratory','pathology']) { const o=makeObservation(modality, modality==='pathology'?'text':'quantity'); assert.equal(o.patientId,'patient-a'); assert.equal(o.value.type,modality==='pathology'?'text':'quantity'); } });
test('controlled values preserve coding, units, and component semantics', () => { assert.throws(()=>diagnosticValue({type:'quantity',value:1}),DomainError); assert.throws(()=>diagnosticValue({type:'unknown',value:'x'}),DomainError); const o=makeObservation('ECG'); const api=observationApi(o); assert.equal(api.code.system,'urn:synthetic'); assert.equal(api.value.unit.code,'synthetic-unit'); });
test('work and result lifecycles reject invalid transitions', () => { const w=workItem({...base,serviceId:'service-a',provenance:p}); assert.equal(transitionWork(w,'scheduled','operator').status,'scheduled'); assert.throws(()=>transitionWork(w,'completed','operator'),DomainError); const o=makeObservation('PFT'); assert.equal(transitionResult(o,'draft','clinician').status,'draft'); assert.throws(()=>transitionResult(o,'amended','clinician'),DomainError); });
test('acquisition, media, interpretation, verification and clinical context preserve traceability', () => { const o=makeObservation('CT'); const binary=mediaObject({mediaType:'application/octet-stream',sizeBytes:12,checksum:'synthetic-checksum',storageClass:'restricted',accessPolicy:'tenant-scoped',provenance:p}); const i=interpretation({...base,sourceObservationIds:[o.id],authorId:'algorithm-a',authorType:'algorithm',narrative:'synthetic',provenance:p}); const v=verification({targetId:o.id,targetType:'observation',verifierId:'clinician',verifiedAt:now,provenance:p}); assert.ok(binary.id && i.id && v.id); assert.equal(assertSameClinicalContext(o,i),true); assert.throws(()=>assertSameClinicalContext(o,{...i,patientId:'patient-b'}),DomainError); });
