/** Step 2: modality-neutral canonical model. Values are validated structurally, never clinically. */
import { id, required, DomainError } from './domain.js';
export { DomainError } from './domain.js';

export const valueTypes = Object.freeze(['integer','decimal','quantity','ratio','range','boolean','code','coded-concept','text','date','date-time','sampled-data','reference','component']);
export const resultTransitions = Object.freeze({ preliminary:['draft','final','cancelled','entered-in-error'], draft:['final','cancelled'], final:['corrected','amended'], corrected:[], amended:[], cancelled:[], 'entered-in-error':[] });
export const workTransitions = Object.freeze({ planned:['scheduled','in-progress','cancelled'], scheduled:['in-progress','cancelled'], 'in-progress':['completed','failed','cancelled'], failed:['planned','cancelled'], completed:[], cancelled:[] });
const timestamp = value => { required(value, 'timestamp'); if (Number.isNaN(Date.parse(value))) throw new DomainError('Timestamp must be ISO-parseable'); return value; };
const scope = ({ organizationId, siteId, patientId }) => ({ organizationId:required(organizationId,'organizationId'), siteId:required(siteId,'siteId'), patientId:required(patientId,'patientId') });
export function coding({ code, system, version = null, display = null, source = 'local' }) { return Object.freeze({ code:required(code,'code'), system:required(system,'coding system'), version, display, source }); }
export function unit({ code, system, display = null }) { return Object.freeze({ code:required(code,'unit code'), system:required(system,'unit system'), display }); }
export function provenance({ sourceType, sourceId, recordedAt, correlationId = null, transformations = [] }) { return Object.freeze({ id:id(), sourceType:required(sourceType,'sourceType'), sourceId:required(sourceId,'sourceId'), recordedAt:timestamp(recordedAt), correlationId, transformations }); }
export function service({ organizationId, code, name, modality = null, category = null, active = true, workflowKey = null, outputKinds = [], identifiers = [] }) { return Object.freeze({ id:id(), organizationId:required(organizationId,'organizationId'), code:coding(code), name:required(name,'service name'), modality, category, active, workflowKey, outputKinds, identifiers }); }
export function workItem({ organizationId, siteId, patientId, orderId, serviceId, departmentId = null, assignedTo = null, deviceId = null, priority = 'routine', scheduledFor = null, provenance: p }) { return { id:id(), ...scope({organizationId,siteId,patientId}), orderId:required(orderId,'orderId'), serviceId:required(serviceId,'serviceId'), departmentId, assignedTo, deviceId, priority, scheduledFor: scheduledFor ? timestamp(scheduledFor) : null, status:'planned', provenance:required(p,'provenance'), createdAt:new Date().toISOString() }; }
export function transitionWork(item, next, actorId) { if (!(workTransitions[item.status] || []).includes(next)) throw new DomainError(`Invalid work transition ${item.status} -> ${next}`); return {...item,status:next,updatedAt:new Date().toISOString(),updatedBy:required(actorId,'actorId')}; }
export function acquisition({ organizationId, siteId, patientId, workItemId, deviceId = null, operatorId = null, status = 'completed', performedAt, rawObject = null, checksum = null, softwareVersion = null, locationId = null, provenance: p }) { return Object.freeze({ id:id(), ...scope({organizationId,siteId,patientId}), workItemId:required(workItemId,'workItemId'), deviceId, operatorId, status, performedAt:timestamp(performedAt), rawObject, checksum, softwareVersion, locationId, provenance:required(p,'provenance') }); }
export function mediaObject({ mediaType, sizeBytes, checksum, storageClass, version = '1', accessPolicy, provenance: p }) { if (!Number.isInteger(sizeBytes) || sizeBytes < 0) throw new DomainError('sizeBytes must be a non-negative integer'); return Object.freeze({ id:id(), mediaType:required(mediaType,'mediaType'), sizeBytes, checksum:required(checksum,'checksum'), storageClass:required(storageClass,'storageClass'), version, accessPolicy:required(accessPolicy,'accessPolicy'), provenance:required(p,'provenance') }); }
export function diagnosticValue({ type, value, valueUnit = null, components = [] }) { if (!valueTypes.includes(type)) throw new DomainError(`Unsupported value type ${type}`); if ((type === 'quantity' || type === 'decimal' || type === 'integer') && typeof value !== 'number') throw new DomainError(`${type} needs numeric value`); if (type === 'quantity' && !valueUnit) throw new DomainError('quantity needs a unit'); if (type === 'component' && !components.length) throw new DomainError('component needs children'); return Object.freeze({ type, value, unit:valueUnit, components }); }
export function observation({ organizationId, siteId, patientId, orderId, acquisitionId = null, encounterId = null, specimenId = null, deviceId = null, performerId = null, code, value, status = 'preliminary', effectiveAt, issuedAt, method = null, interpretation = null, referenceRange = null, provenance: p, parentId = null }) { return { id:id(), ...scope({organizationId,siteId,patientId}), orderId:required(orderId,'orderId'), acquisitionId, encounterId, specimenId, deviceId, performerId, code:coding(code), value:diagnosticValue(value), status, effectiveAt:timestamp(effectiveAt), issuedAt:timestamp(issuedAt), method, interpretation, referenceRange, parentId, provenance:required(p,'provenance'), version:1 }; }
export function study({ organizationId, siteId, patientId, orderId, modality = null, accessionIdentifiers = [], acquisitionIds = [], provenance: p }) { return Object.freeze({ id:id(), ...scope({organizationId,siteId,patientId}), orderId:required(orderId,'orderId'), modality, accessionIdentifiers, acquisitionIds, provenance:required(p,'provenance') }); }
export function interpretation({ organizationId, siteId, patientId, orderId, sourceObservationIds, authorId, authorType, narrative = null, status = 'draft', provenance: p }) { if (!['human','algorithm','device'].includes(authorType)) throw new DomainError('Unknown interpreter type'); return { id:id(),...scope({organizationId,siteId,patientId}),orderId:required(orderId,'orderId'),sourceObservationIds,authorId:required(authorId,'authorId'),authorType,narrative,status,provenance:required(p,'provenance'),createdAt:new Date().toISOString() }; }
export function transitionResult(record, next, actorId) { if (!(resultTransitions[record.status] || []).includes(next)) throw new DomainError(`Invalid result transition ${record.status} -> ${next}`); return {...record,status:next,version:(record.version || 1)+1,updatedAt:new Date().toISOString(),updatedBy:required(actorId,'actorId')}; }
export function verification({ targetId, targetType, verifierId, verifiedAt, method = null, provenance: p }) { return Object.freeze({ id:id(),targetId:required(targetId,'targetId'),targetType:required(targetType,'targetType'),verifierId:required(verifierId,'verifierId'),verifiedAt:timestamp(verifiedAt),method,provenance:required(p,'provenance') }); }
export function assertSameClinicalContext(...resources) { const first=resources[0]; for (const resource of resources.slice(1)) for (const key of ['organizationId','siteId','patientId','orderId']) if (first[key] && resource[key] && first[key] !== resource[key]) throw new DomainError(`Clinical context mismatch: ${key}`); return true; }
