/** Step 5 ECG boundary. Metadata/object references only; no waveform samples or clinical interpretation. */
import {id,required,DomainError} from './domain.js';
const scope=(x,c)=>x.organizationId===c.organizationId&&x.siteId===c.siteId;
export class EcgModule{
 #waveforms=new Map();#keys=new Map();
 ingestWaveform({organizationId,siteId,patientId,orderId,workItemId,acquisitionId,deviceId,sourceId,objectId,checksum,format,formatVersion,samplingFrequency,leads,provenance},context){for(const k of ['actorId','organizationId','siteId'])required(context?.[k],`context.${k}`);if(!scope({organizationId,siteId},context))throw new DomainError('ECG tenant scope violation');if(!Array.isArray(leads)||!leads.length)throw new DomainError('ECG waveform requires lead metadata');if(!Number.isFinite(samplingFrequency)||samplingFrequency<=0)throw new DomainError('ECG sampling frequency is required');for(const l of leads)if(!l.id||!Number.isInteger(l.sampleCount)||l.sampleCount<1||!l.unit)throw new DomainError('Invalid ECG lead metadata');const key=`${deviceId}:${sourceId}`;if(this.#keys.has(key))return {...this.#keys.get(key),idempotent:true};const w={id:id(),organizationId,siteId,patientId:required(patientId,'patientId'),orderId:required(orderId,'orderId'),workItemId:required(workItemId,'workItemId'),acquisitionId:required(acquisitionId,'acquisitionId'),deviceId:required(deviceId,'deviceId'),sourceId:required(sourceId,'sourceId'),objectId:required(objectId,'objectId'),checksum:required(checksum,'checksum'),format:required(format,'format'),formatVersion:required(formatVersion,'formatVersion'),samplingFrequency,leads,provenance:required(provenance,'provenance'),receivedAt:new Date().toISOString()};this.#waveforms.set(w.id,w);this.#keys.set(key,w);return {...w};}
 getWaveform(id,context){const w=this.#waveforms.get(id);if(!w||!scope(w,context))throw new DomainError('Unknown or unauthorized ECG waveform');return {...w};}
 measurement({waveformId,code,value,unit,sourceType,observedAt,provenance},context){const w=this.getWaveform(waveformId,context);if(!['device','algorithm','human'].includes(sourceType))throw new DomainError('Unknown measurement source');if(typeof value!=='number'||!unit||!code)throw new DomainError('Measurement requires explicit numeric value, code, and unit');return {id:id(),waveformId:w.id,patientId:w.patientId,orderId:w.orderId,code,value,unit,sourceType,observedAt:required(observedAt,'observedAt'),provenance:required(provenance,'provenance')};}
}
