/** Step 4 operational workflow. Pure domain proof; persistence, RLS, API, and UI remain adapters. */
import { id, required, DomainError } from './domain.js';

export const workflowStates=Object.freeze({ready:['scheduled','assigned','cancelled'],scheduled:['assigned','in-progress','cancelled'],assigned:['in-progress','ready','cancelled'], 'in-progress':['acquired','failed','cancelled'],acquired:['processing','completed','failed'],processing:['completed','failed'],completed:[],failed:['ready','cancelled'],cancelled:[]});
const ctx=c=>{for(const k of ['actorId','organizationId','siteId']) required(c?.[k],`context.${k}`);return c}; const scoped=(x,c)=>x.organizationId===c.organizationId&&x.siteId===c.siteId; const now=()=>new Date().toISOString();
export class WorkflowEngine {
 #work=new Map(); #orderKeys=new Map(); #audit=[];
 createFromOrder({organizationId,siteId,patientId,orderId,serviceId,departmentId=null,priority='routine',requestedAt,provenance,idempotencyKey},context){ctx(context); if(!scoped({organizationId,siteId},context))throw new DomainError('Forged work scope'); const key=`${organizationId}:${siteId}:${required(idempotencyKey,'idempotencyKey')}`; if(this.#orderKeys.has(key))return {...this.#orderKeys.get(key),idempotent:true}; const w={id:id(),organizationId,siteId,patientId:required(patientId,'patientId'),orderId:required(orderId,'orderId'),serviceId:required(serviceId,'serviceId'),departmentId,priority,requestedAt:required(requestedAt,'requestedAt'),status:'ready',provenance:required(provenance,'provenance'),assignment:null,schedule:null,lease:null,createdAt:now()};this.#work.set(w.id,w);this.#orderKeys.set(key,w);this.#event(context,'work.created',w.id);return {...w};}
 get(id,context){ctx(context);const w=this.#work.get(id);if(!w||!scoped(w,context))throw new DomainError('Unknown or unauthorized work');return {...w};}
 schedule(id,{start,end,resourceId=null},context){const w=this.get(id,context);if(!['ready','scheduled'].includes(w.status))throw new DomainError('Work is not schedulable');if(!start||!end||Date.parse(end)<=Date.parse(start))throw new DomainError('Invalid schedule interval');for(const x of this.#work.values())if(x.id!==id&&scoped(x,context)&&resourceId&&x.schedule?.resourceId===resourceId&&x.status!=='cancelled'&&Date.parse(start)<Date.parse(x.schedule.end)&&Date.parse(end)>Date.parse(x.schedule.start))throw new DomainError('Resource schedule conflict');return this.#change(w,{status:'scheduled',schedule:{start,end,resourceId}},context,'work.scheduled');}
 assign(id,{operatorId=null,deviceId=null,resourceId=null,deviceRegistry=null},context){const w=this.get(id,context);if(!['ready','scheduled','assigned'].includes(w.status))throw new DomainError('Work is not assignable');if(deviceId&&deviceRegistry){const d=deviceRegistry.getDevice(deviceId,context);if(d.status!=='active')throw new DomainError('Device is not active');}return this.#change(w,{status:'assigned',assignment:{operatorId,deviceId,resourceId,assignedBy:context.actorId,assignedAt:now()}},context,'work.assigned');}
 claim(id,{operatorId,expiresAt},context){const w=this.get(id,context);if(!['ready','scheduled','assigned'].includes(w.status))throw new DomainError('Work is not claimable');if(w.lease&&Date.parse(w.lease.expiresAt)>Date.now()&&w.lease.ownerId!==operatorId)throw new DomainError('Work is already claimed');if(Date.parse(expiresAt)<=Date.now())throw new DomainError('Lease must expire in the future');return this.#change(w,{status:'assigned',lease:{ownerId:required(operatorId,'operatorId'),claimedAt:now(),expiresAt}},context,'work.claimed');}
 release(id,context){const w=this.get(id,context);if(!w.lease||w.lease.ownerId!==context.actorId)throw new DomainError('Only lease owner can release');return this.#change(w,{lease:null},context,'work.released');}
 transition(id,next,context,{reason=null}={}){const w=this.get(id,context);if(!(workflowStates[w.status]||[]).includes(next))throw new DomainError(`Invalid workflow transition ${w.status} -> ${next}`);if(next==='in-progress'&&w.lease&&w.lease.ownerId!==context.actorId)throw new DomainError('Lease owner required to start acquisition');const stamps=next==='in-progress'?{actualStart:now()}:next==='acquired'?{acquiredAt:now()}:next==='processing'?{processingAt:now()}:next==='completed'?{completedAt:now()}:next==='failed'?{failedAt:now(),failureReason:required(reason,'failure reason')}:next==='cancelled'?{cancelledAt:now(),cancellationReason:required(reason,'cancellation reason')}:{};return this.#change(w,{status:next,...stamps},context,`work.${next}`);}
 worklist(filters,context){ctx(context);return [...this.#work.values()].filter(w=>scoped(w,context)).filter(w=>!filters?.status||w.status===filters.status).filter(w=>!filters?.departmentId||w.departmentId===filters.departmentId).filter(w=>!filters?.priority||w.priority===filters.priority).filter(w=>!filters?.deviceId||w.assignment?.deviceId===filters.deviceId).map(w=>({id:w.id,status:w.status,priority:w.priority,departmentId:w.departmentId,scheduledStart:w.schedule?.start||null,assignedOperatorId:w.assignment?.operatorId||null,deviceId:w.assignment?.deviceId||null}));}
 audit(context){ctx(context);return this.#audit.filter(x=>scoped(x,context)).map(x=>({...x}));}
 #change(w,changes,context,action){const updated={...w,...changes,updatedAt:now(),updatedBy:context.actorId};this.#work.set(w.id,updated);this.#event(context,action,w.id);return {...updated};} #event(context,action,workId){this.#audit.push({id:id(),at:now(),actorId:context.actorId,organizationId:context.organizationId,siteId:context.siteId,action,workId,correlationId:context.correlationId||null});}
}
